version: '3.8'

services:
  web:
    image: php:8.1-apache
    container_name: phpoo-web
    ports:
      - "8080:80"
    volumes:
      - ./phpoo:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: phpoo-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: phpoodb
      MYSQL_USER: phpuser
      MYSQL_PASSWORD: phppassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
